services:
   unoegohh.admin.admin.page:
      class: Unoegohh\AdminBundle\Admin\PageAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: 'Основное', label: 'Страницы' }
      arguments: [null, Unoegohh\AdminBundle\Entity\Page, UnoegohhAdminBundle:Page]
   unoegohh.admin.admin.product:
      class: Unoegohh\AdminBundle\Admin\ProductAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: 'Товары', label: 'Продукты' }
      arguments: [null, Unoegohh\AdminBundle\Entity\Product, UnoegohhAdminBundle:Product]
   unoegohh.admin.admin.productCategory:
      class: Unoegohh\AdminBundle\Admin\ProductCategoryAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: 'Товары', label: 'Категории' }
      arguments: [null, Unoegohh\AdminBundle\Entity\ProductCategory, UnoegohhAdminBundle:ProductCategory]
   unoegohh.admin.admin.productPhoto:
      class: Unoegohh\AdminBundle\Admin\ProductPhotoAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: 'Товары', label: 'Фотографии' }
      arguments: [null, Unoegohh\AdminBundle\Entity\ProductPhoto, UnoegohhAdminBundle:ProductPhoto]