parameters:
#    unoegohh_admin.example.class: Unoegohh\AdminBundle\Example

services:
#    unoegohh_admin.example:
#        class: %unoegohh_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
